"""Initial migration.

Revision ID: c61bda9317ec
Revises: 
Create Date: 2024-07-10 22:46:28.339149

"""
from alembic import op
import sqlalchemy as sa


# Define el nombre de la tabla
table_name = 'user'

# revision identifiers, used by Alembic.
revision = 'c61bda9317ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crea la tabla 'user' si no existe
    op.create_table(
        table_name,
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('calculated_rating', sa.Float(precision=2), nullable=True),
        # Otros campos de la tabla 'user' aquí
    )
    
    # Altera la columna 'calculated_rating'
    with op.batch_alter_table(table_name, schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name, schema=None) as batch_op:
        batch_op.alter_column('calculated_rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    
    # Elimina la tabla 'user' en la migración de downgrade
    op.drop_table(table_name)

    # ### end Alembic commands ###

